naver:
  client:
    id: VwUj60Ba7ZJkWWP40LY0
    secret: m22rG90pni
  redirect:
    uri: http://localhost:80/login/oauth2/code/naver
  authorization:
    uri: https://nid.naver.com/oauth2.0/authorize
  token:
    uri: https://nid.naver.com/oauth2.0/token
    grant-type: authorization_code
  profile:
    uri: https://openapi.naver.com/v1/nid/me